enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

[YouTube-Extended]
enabled = true
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "module"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
